[versions]
# Plugins
loom = "1.6-SNAPSHOT"
kotlin = "1.9.23"
yamlang = "1.4.+"
mpp = "0.4.+"
# MC setup
minecraft = "1.20.6"
vineflower = "1.10.0"
fabric-loader = "0.15.10"
fabric-yarn = "1.20.6+build.1"
fabric-api = "0.97.8+1.20.6"
fabric-language-kotlin = "1.10.19+kotlin.1.9.23"
# Dependencies

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "loom" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
yamlang = { id = "dev.kikugie.yamlang", version.ref = "yamlang" }
mpp = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mpp" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
vineflower = { group = "org.vineflower", name = "vineflower", version.ref = "vineflower" }
fabric-yarn = { group = "net.fabricmc", name = "yarn", version.ref = "fabric-yarn" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-language-kotlin" }
